# Generated by Django 5.1.7 on 2026-01-28 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_institution_inst_category_institution_inst_type'),
        ('users', '0002_verificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.institution'),
        ),
    ]
