# Generated by Django 5.1.7 on 2026-01-21 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Circle', 'verbose_name_plural': 'Circles'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'The Drop', 'verbose_name_plural': 'The Drops'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'The Plug', 'verbose_name_plural': 'The Plugs'},
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_details', models.TextField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='store.store')),
            ],
        ),
    ]
