# Generated by Django 5.1.7 on 2026-01-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_image2_product_image3_product_image4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='delivery_fee',
            new_name='campus_delivery_fee',
        ),
        migrations.AddField(
            model_name='product',
            name='waybill_delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
