import os
import django
from django.utils.text import slugify

# Setup Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'tribe_trade_backend.settings')
django.setup()

from core.models import Institution

def seed_institutions():
    print("--- Seeding Comprehensive Institution List ---")

    institutions_data = [
        # FEDERAL UNIVERSITIES
        ("Abubakar Tafawa Balewa University, Bauchi", "university", "federal"),
        ("Ahmadu Bello University, Zaria", "university", "federal"),
        ("Bayero University, Kano", "university", "federal"),
        ("Federal University, Birnin-Kebbi", "university", "federal"),
        ("Federal University, Dutse", "university", "federal"),
        ("Federal University, Dutsin-Ma", "university", "federal"),
        ("Federal University, Gashua", "university", "federal"),
        ("Federal University, Gusau", "university", "federal"),
        ("Federal University, Kashere", "university", "federal"),
        ("Federal University, Lafia", "university", "federal"),
        ("Federal University, Lokoja", "university", "federal"),
        ("Federal University, Oye-Ekiti", "university", "federal"),
        ("Federal University, Otuoke", "university", "federal"),
        ("Federal University, Wukari", "university", "federal"),
        ("Federal University of Agriculture, Abeokuta", "university", "federal"),
        ("Federal University of Health Sciences, Azare", "university", "federal"),
        ("Federal University of Health Sciences, Ila-Orangun", "university", "federal"),
        ("Federal University of Health Sciences, Otukpo", "university", "federal"),
        ("Federal University of Petroleum Resources, Effurun", "university", "federal"),
        ("Federal University of Technology, Akure", "university", "federal"),
        ("Federal University of Technology, Babura", "university", "federal"),
        ("Federal University of Technology, Ikot Abasi", "university", "federal"),
        ("Federal University of Technology, Minna", "university", "federal"),
        ("Federal University of Technology, Owerri", "university", "federal"),
        ("Federal University of Transportation, Daura", "university", "federal"),
        ("Joseph Sarwuan Tarka University, Makurdi", "university", "federal"),
        ("Michael Okpara University of Agriculture, Umudike", "university", "federal"),
        ("Modibbo Adama University, Yola", "university", "federal"),
        ("National Open University of Nigeria, Abuja", "university", "federal"),
        ("Nigeria Police Academy, Wudil", "university", "federal"),
        ("Nigerian Army University, Biu", "university", "federal"),
        ("Nigerian Defence Academy, Kaduna", "university", "federal"),
        ("Nnamdi Azikiwe University, Awka", "university", "federal"),
        ("Obafemi Awolowo University, Ile-Ife", "university", "federal"),
        ("University of Abuja, Gwagwalada", "university", "federal"),
        ("University of Benin, Benin City", "university", "federal"),
        ("University of Calabar, Calabar", "university", "federal"),
        ("University of Ibadan, Ibadan", "university", "federal"),
        ("University of Ilorin, Ilorin", "university", "federal"),
        ("University of Jos, Jos", "university", "federal"),
        ("University of Lagos, Akoka", "university", "federal"),
        ("University of Maiduguri, Maiduguri", "university", "federal"),
        ("University of Nigeria, Nsukka", "university", "federal"),
        ("University of Port Harcourt, Port Harcourt", "university", "federal"),
        ("University of Uyo, Uyo", "university", "federal"),
        ("Usmanu Danfodiyo University, Sokoto", "university", "federal"),
        ("Admiralty University of Nigeria, Ibusa", "university", "federal"),
        ("Adeyemi Federal University of Education, Ondo", "university", "federal"),
        ("Alvan Ikoku Federal University of Education, Owerri", "university", "federal"),
        ("Federal University of Education, Kano", "university", "federal"),
        ("Federal University of Education, Zaria", "university", "federal"),
        ("Federal University of Education, Pankshin", "university", "federal"),
        ("Federal University of Education, Kontagora", "university", "federal"),
        ("Federal University of Education, Ila-Orangun", "university", "federal"),

        # STATE UNIVERSITIES
        ("Abia State University, Uturu", "university", "state"),
        ("Adamawa State University, Mubi", "university", "state"),
        ("Adekunle Ajasin University, Akungba-Akoko", "university", "state"),
        ("Akwa Ibom State University, Ikot-Akpaden", "university", "state"),
        ("Ambrose Alli University, Ekpoma", "university", "state"),
        ("Abdulkadir Kure University, Minna", "university", "state"),
        ("Bauchi State University, Gadau", "university", "state"),
        ("Bayelsa Medical University, Yenagoa", "university", "state"),
        ("Benue State University, Makurdi", "university", "state"),
        ("Borno State University, Maiduguri", "university", "state"),
        ("Chukwuemeka Odumegwu Ojukwu University, Uli", "university", "state"),
        ("Confluence University of Science and Technology, Osara", "university", "state"),
        ("Delta State University, Abraka", "university", "state"),
        ("Delta State University of Science and Technology, Ozoro", "university", "state"),
        ("Dennis Osadebay University, Asaba", "university", "state"),
        ("Ebonyi State University, Abakaliki", "university", "state"),
        ("Edo State University, Uzairue", "university", "state"),
        ("Ekiti State University, Ado-Ekiti", "university", "state"),
        ("Emmanuel Alayande University of Education, Oyo", "university", "state"),
        ("Enugu State University of Science and Technology, Enugu", "university", "state"),
        ("Gombe State University, Tudun Wada", "university", "state"),
        ("Gombe State University of Science and Technology, Kumo", "university", "state"),
        ("Ibrahim Badamasi Babangida University, Lapai", "university", "state"),
        ("Ignatius Ajuru University of Education, Port Harcourt", "university", "state"),
        ("Imo State University, Owerri", "university", "state"),
        ("Kaduna State University, Kaduna", "university", "state"),
        ("Aliko Dangote University of Science and Technology, Wudil", "university", "state"),
        ("Kebbi State University of Science and Technology, Aliero", "university", "state"),
        ("Kingsley Ozumba Mbadiwe University, Ogboko", "university", "state"),
        ("Kwara State University, Malete", "university", "state"),
        ("Ladoke Akintola University of Technology, Ogbomoso", "university", "state"),
        ("Lagos State University, Ojo", "university", "state"),
        ("Lagos State University of Education, Ijanikin/Epe", "university", "state"),
        ("Lagos State University of Science and Technology, Ikorodu", "university", "state"),
        ("Nasarawa State University, Keffi", "university", "state"),
        ("Niger Delta University, Wilberforce Island", "university", "state"),
        ("Yusuf Maitama Sule University, Kano", "university", "state"),
        ("Olabisi Onabanjo University, Ago-Iwoye", "university", "state"),
        ("Olusegun Agagu University of Science and Technology, Okitipupa", "university", "state"),
        ("Osun State University, Osogbo", "university", "state"),
        ("Plateau State University, Bokkos", "university", "state"),
        ("Prince Abubakar Audu University, Anyigba", "university", "state"),
        ("Rivers State University, Port Harcourt", "university", "state"),
        ("Sa’adatu Rimi University of Education, Kano", "university", "state"),
        ("Shehu Shagari University of Education, Sokoto", "university", "state"),
        ("Sokoto State University, Sokoto", "university", "state"),
        ("Tai Solarin University of Education, Ijagun", "university", "state"),
        ("Taraba State University, Jalingo", "university", "state"),
        ("Umaru Musa Yar’Adua University, Katsina", "university", "state"),
        ("University of Cross River State, Calabar", "university", "state"),
        ("University of Delta, Agbor", "university", "state"),
        ("University of Ilesa, Osun State", "university", "state"),
        ("Yobe State University, Damaturu", "university", "state"),
        ("Zamfara State University, Talata-Mafara", "university", "state"),

        # PRIVATE UNIVERSITIES
        ("Achievers University, Owo", "university", "private"),
        ("Adeleke University, Ede", "university", "private"),
        ("Afe Babalola University, Ado-Ekiti", "university", "private"),
        ("Ajayi Crowther University, Oyo", "university", "private"),
        ("Al-Hikmah University, Ilorin", "university", "private"),
        ("American University of Nigeria, Yola", "university", "private"),
        ("Anchor University, Lagos", "university", "private"),
        ("Augustine University, Ilara", "university", "private"),
        ("Babcock University, Ilishan-Remo", "university", "private"),
        ("Baze University, Abuja", "university", "private"),
        ("Bell's University of Technology, Ota", "university", "private"),
        ("Benson Idahosa University, Benin City", "university", "private"),
        ("Bingham University, Karu", "university", "private"),
        ("Bowen University, Iwo", "university", "private"),
        ("Caleb University, Imota", "university", "private"),
        ("Caritas University, Amorji-Nike", "university", "private"),
        ("Chrisland University, Owode", "university", "private"),
        ("Coal City University, Enugu", "university", "private"),
        ("Covenant University, Ota", "university", "private"),
        ("Crawford University, Igbesa", "university", "private"),
        ("Crescent University, Abeokuta", "university", "private"),
        ("Elizade University, Ilara-Mokin", "university", "private"),
        ("Fountain University, Osogbo", "university", "private"),
        ("Godfrey Okoye University, Ugwuomu-Nike", "university", "private"),
        ("Gregory University, Uturu", "university", "private"),
        ("Hallmark University, Ijebu-Itele", "university", "private"),
        ("Hezekiah University, Umudi", "university", "private"),
        ("Igbinedion University, Okada", "university", "private"),
        ("Joseph Ayo Babalola University, Ikeji-Arakeji", "university", "private"),
        ("Kola Daisi University, Ibadan", "university", "private"),
        ("Landmark University, Omu-Aran", "university", "private"),
        ("Lead City University, Ibadan", "university", "private"),
        ("Madonna University, Okija", "university", "private"),
        ("McPherson University, Seriki Sotayo", "university", "private"),
        ("Mountain Top University, Ogun State", "university", "private"),
        ("Nile University of Nigeria, Abuja", "university", "private"),
        ("Novena University, Ogume", "university", "private"),
        ("Oduduwa University, Ipetumodu", "university", "private"),
        ("Pan-Atlantic University, Lagos", "university", "private"),
        ("Paul University, Awka", "university", "private"),
        ("Redeemer’s University, Ede", "university", "private"),
        ("Renaissance University, Ugbawka", "university", "private"),
        ("Rhema University, Aba", "university", "private"),
        ("Ritman University, Ikot-Ekpene", "university", "private"),
        ("Salem University, Lokoja", "university", "private"),
        ("Skyline University Nigeria, Kano", "university", "private"),
        ("Summit University, Offa", "university", "private"),
        ("Tansian University, Umunya", "university", "private"),
        ("Veritas University, Abuja", "university", "private"),
        ("Wellspring University, Benin City", "university", "private"),
        ("Western Delta University, Oghara", "university", "private"),
        ("Wigwe University, Isiokpo", "university", "private"),

        # FEDERAL POLYTECHNICS
        ("Akanu Ibiam Federal Polytechnic, Unwana", "polytechnic", "federal"),
        ("Auchi Polytechnic, Auchi", "polytechnic", "federal"),
        ("Federal Polytechnic, Ado-Ekiti", "polytechnic", "federal"),
        ("Federal Polytechnic, Bali", "polytechnic", "federal"),
        ("Federal Polytechnic, Bauchi", "polytechnic", "federal"),
        ("Federal Polytechnic, Bida", "polytechnic", "federal"),
        ("Federal Polytechnic, Damaturu", "polytechnic", "federal"),
        ("Federal Polytechnic, Daura", "polytechnic", "federal"),
        ("Federal Polytechnic, Ede", "polytechnic", "federal"),
        ("Federal Polytechnic, Ekowe", "polytechnic", "federal"),
        ("Federal Polytechnic, Idah", "polytechnic", "federal"),
        ("Federal Polytechnic, Ilaro", "polytechnic", "federal"),
        ("Federal Polytechnic, Ile-Oluji", "polytechnic", "federal"),
        ("Federal Polytechnic, Kaura Namoda", "polytechnic", "federal"),
        ("Federal Polytechnic, Kaltungo", "polytechnic", "federal"),
        ("Federal Polytechnic, Mubi", "polytechnic", "federal"),
        ("Federal Polytechnic, Nasarawa", "polytechnic", "federal"),
        ("Federal Polytechnic, Nekede", "polytechnic", "federal"),
        ("Federal Polytechnic, Offa", "polytechnic", "federal"),
        ("Federal Polytechnic, Oko", "polytechnic", "federal"),
        ("Federal Polytechnic, Paraku", "polytechnic", "federal"),
        ("Federal Polytechnic, Ukana", "polytechnic", "federal"),
        ("Federal Polytechnic, Wannune", "polytechnic", "federal"),
        ("Hussaini Adamu Federal Polytechnic, Kazaure", "polytechnic", "federal"),
        ("Kaduna Polytechnic, Kaduna", "polytechnic", "federal"),
        ("Waziri Umaru Federal Polytechnic, Birnin Kebbi", "polytechnic", "federal"),
        ("Yaba College of Technology, Lagos", "polytechnic", "federal"),

        # STATE POLYTECHNICS
        ("Abdu Gusau Polytechnic, Talata Mafara", "polytechnic", "state"),
        ("Abia State Polytechnic, Aba", "polytechnic", "state"),
        ("Abraham Adesanya Polytechnic, Ijebu-Igbo", "polytechnic", "state"),
        ("Abubakar Tatari Ali Polytechnic, Bauchi", "polytechnic", "state"),
        ("Adamawa State Polytechnic, Yola", "polytechnic", "state"),
        ("Akwa Ibom State Polytechnic, Ikot Osurua", "polytechnic", "state"),
        ("Benue State Polytechnic, Ugbokolo", "polytechnic", "state"),
        ("Binyaminu Usman Polytechnic, Hadejia", "polytechnic", "state"),
        ("Delta State Polytechnic, Ogwashi-Uku", "polytechnic", "state"),
        ("Delta State Polytechnic, Otefe-Oghara", "polytechnic", "state"),
        ("DS Adegbenro ICT Polytechnic, Itori", "polytechnic", "state"),
        ("Edo State Polytechnic, Usen", "polytechnic", "state"),
        ("Enugu State Polytechnic, Iwollo", "polytechnic", "state"),
        ("Gateway ICT Polytechnic, Saapade", "polytechnic", "state"),
        ("Hassan Usman Katsina Polytechnic, Katsina", "polytechnic", "state"),
        ("Imo State Polytechnic, Omuma", "polytechnic", "state"),
        ("Institute of Management and Technology (IMT), Enugu", "polytechnic", "state"),
        ("Jigawa State Polytechnic, Dutse", "polytechnic", "state"),
        ("Kano State Polytechnic, Kano", "polytechnic", "state"),
        ("Ken Saro-Wiwa Polytechnic, Bori", "polytechnic", "state"),
        ("Kogi State Polytechnic, Lokoja", "polytechnic", "state"),
        ("Kwara State Polytechnic, Ilorin", "polytechnic", "state"),
        ("Moshood Abiola Polytechnic, Abeokuta", "polytechnic", "state"),
        ("Isa Mustapha Agwai I Polytechnic, Lafia", "polytechnic", "state"),
        ("Niger State Polytechnic, Zungeru", "polytechnic", "state"),
        ("Nuhu Bamalli Polytechnic, Zaria", "polytechnic", "state"),
        ("Ogun State Institute of Technology, Igbesa", "polytechnic", "state"),
        ("Osun State College of Technology, Esa-Oke", "polytechnic", "state"),
        ("Osun State Polytechnic, Iree", "polytechnic", "state"),
        ("Plateau State Polytechnic, Barkin Ladi", "polytechnic", "state"),
        ("Captain Elechi Amadi Polytechnic, Port Harcourt", "polytechnic", "state"),
        ("Ramat Polytechnic, Maiduguri", "polytechnic", "state"),
        ("Rufus Giwa Polytechnic, Owo", "polytechnic", "state"),
        ("Sokoto State Polytechnic, Sokoto", "polytechnic", "state"),
        ("Taraba State Polytechnic, Suntai", "polytechnic", "state"),
        ("The Polytechnic, Ibadan", "polytechnic", "state"),
        ("Umaru Ali Shinkafi Polytechnic, Sokoto", "polytechnic", "state"),
        ("Zamfara State College of Arts and Science", "polytechnic", "state"),

        # PRIVATE POLYTECHNICS
        ("Alover Central Polytechnic, Ota", "polytechnic", "private"),
        ("Ajayi Polytechnic, Ikere-Ekiti", "polytechnic", "private"),
        ("Best Solution Polytechnic, Akure", "polytechnic", "private"),
        ("Bolmor Polytechnic, Ibadan", "polytechnic", "private"),
        ("Covenant Polytechnic, Aba", "polytechnic", "private"),
        ("Crown Polytechnic, Ado-Ekiti", "polytechnic", "private"),
        ("Dorben Polytechnic, Abuja", "polytechnic", "private"),
        ("Eastern Polytechnic, Port Harcourt", "polytechnic", "private"),
        ("Fidei Polytechnic, Gboko", "polytechnic", "private"),
        ("Grace Polytechnic, Lagos", "polytechnic", "private"),
        ("Heritage Polytechnic, Eket", "polytechnic", "private"),
        ("Igbajo Polytechnic, Igbajo", "polytechnic", "private"),
        ("Interlink Polytechnic, Ijebu-Jesa", "polytechnic", "private"),
        ("Kings Polytechnic, Ubiaja", "polytechnic", "private"),
        ("Lagos City Polytechnic, Ikeja", "polytechnic", "private"),
        ("Lens Polytechnic, Offa", "polytechnic", "private"),
        ("Lighthouse Polytechnic, Evbuobanosa", "polytechnic", "private"),
        ("Maranatha Polytechnic, Lagos", "polytechnic", "private"),
        ("Nacabs Polytechnic, Akwanga", "polytechnic", "private"),
        ("Nogak Polytechnic, Ikom", "polytechnic", "private"),
        ("Ronik Polytechnic, Lagos", "polytechnic", "private"),
        ("Shaka Polytechnic, Benin City", "polytechnic", "private"),
        ("Temple Gate Polytechnic, Aba", "polytechnic", "private"),
        ("The Polytechnic, Igbo-Owu", "polytechnic", "private"),
        ("The Polytechnic, Imesi-Ile", "polytechnic", "private"),
        ("Tower Polytechnic, Ibadan", "polytechnic", "private"),
        ("Uma Ukpai Polytechnic, Asaga Ohafia", "polytechnic", "private"),
        ("Uyo City Polytechnic, Uyo", "polytechnic", "private"),
        ("Wolex Polytechnic, Lagos", "polytechnic", "private"),

        # FEDERAL COLLEGES OF EDUCATION
        ("Federal College of Education, Abeokuta", "college_of_education", "federal"),
        ("Federal College of Education, Eha-Amufu", "college_of_education", "federal"),
        ("Federal College of Education, Katsina", "college_of_education", "federal"),
        ("Federal College of Education, Obudu", "college_of_education", "federal"),
        ("Federal College of Education, Okene", "college_of_education", "federal"),
        ("Federal College of Education, Yola", "college_of_education", "federal"),
        ("Federal College of Education (Special), Oyo", "college_of_education", "federal"),
        ("Federal College of Education (Technical), Akoka", "college_of_education", "federal"),
        ("Federal College of Education (Technical), Asaba", "college_of_education", "federal"),
        ("Federal College of Education (Technical), Bichi", "college_of_education", "federal"),
        ("Federal College of Education (Technical), Gombe", "college_of_education", "federal"),
        ("Federal College of Education (Technical), Gusau", "college_of_education", "federal"),
        ("Federal College of Education (Technical), Omoku", "college_of_education", "federal"),
        ("Federal College of Education (Technical), Potiskum", "college_of_education", "federal"),
        ("Federal College of Education (Technical), Umunze", "college_of_education", "federal"),
        ("Federal College of Education, Iwo, Osun State", "college_of_education", "federal"),
        ("Federal College of Education, Gidan Madi, Sokoto State", "college_of_education", "federal"),
        ("Federal College of Education, Odugbo, Benue State", "college_of_education", "federal"),
        ("Federal College of Education, Isu, Ebonyi State", "college_of_education", "federal"),
        ("Federal College of Education, Ofeme, Abia State", "college_of_education", "federal"),
        ("Federal College of Education, Ilawe Ekiti, Ekiti State", "college_of_education", "federal"),

        # STATE COLLEGES OF EDUCATION
        ("Adamawa State College of Education, Hong", "college_of_education", "state"),
        ("Adamu Augie College of Education, Argungu", "college_of_education", "state"),
        ("Akwa Ibom State College of Education, Afaha Nsit", "college_of_education", "state"),
        ("Aminu Saleh College of Education, Azare", "college_of_education", "state"),
        ("Borno State College of Education, Maiduguri", "college_of_education", "state"),
        ("College of Education, Akwanga", "college_of_education", "state"),
        ("College of Education, Agbor", "college_of_education", "state"),
        ("Tayo Akpata University of Education, Ekiadolor", "college_of_education", "state"),
        ("College of Education, Gindiri", "college_of_education", "state"),
        ("Bamidele Olumilua University of Education, Ikere-Ekiti", "college_of_education", "state"),
        ("College of Education, Katsina-Ala", "college_of_education", "state"),
        ("College of Education, Lanlate", "college_of_education", "state"),
        ("College of Education, Minna", "college_of_education", "state"),
        ("College of Education, Oju", "college_of_education", "state"),
        ("College of Education, Warri", "college_of_education", "state"),
        ("College of Education, Waka-Biu", "college_of_education", "state"),
        ("College of Education, Zing", "college_of_education", "state"),
        ("Cross River State College of Education, Akamkpa", "college_of_education", "state"),
        ("Delta State College of Education, Mosogar", "college_of_education", "state"),
        ("Ebonyi State College of Education, Ikwo", "college_of_education", "state"),
        ("Edo State College of Education, Igueben", "college_of_education", "state"),
        ("Enugu State College of Education (Technical), Enugu", "college_of_education", "state"),
        ("Isaac Jasper Boro College of Education, Sagbama", "college_of_education", "state"),
        ("Jigawa State College of Education, Gumel", "college_of_education", "state"),
        ("Kaduna State College of Education, Gidan Waya", "college_of_education", "state"),
        ("Kano State College of Education, Kumbotso", "college_of_education", "state"),
        ("Kashim Ibrahim College of Education, Maiduguri", "college_of_education", "state"),
        ("Kwara State College of Education, Ilorin", "college_of_education", "state"),
        ("Kwara State College of Education, Oro", "college_of_education", "state"),
        ("Michael Otedola College of Primary Education, Noforija-Epe", "college_of_education", "state"),
        ("Nwafor Orizu College of Education, Nsugbe", "college_of_education", "state"),
        ("Tai Solarin College of Education, Omu-Ijebu", "college_of_education", "state"),
        ("Osun State College of Education, Ila-Orangun", "college_of_education", "state"),
        ("University of Ilesa, Ilesa", "college_of_education", "state"),
        ("Umar Ibn El-Kanemi College of Education, Bama", "college_of_education", "state"),
        ("Zamfara State College of Education, Maru", "college_of_education", "state"),

        # PRIVATE COLLEGES OF EDUCATION
        ("African Thinkers Community of Inquiry College of Education, Enugu", "college_of_education", "private"),
        ("Angel Michael College of Education, Sub-Lime, Lafia", "college_of_education", "private"),
        ("Ansar-Ud-Deen College of Education, Isolo", "college_of_education", "private"),
        ("Arabic and Islamic College of Education, Potiskum", "college_of_education", "private"),
        ("Assanusiyah College of Education, Odeomu", "college_of_education", "private"),
        ("Best Legacy College of Education, Ogbomoso", "college_of_education", "private"),
        ("Calvin Foundation College of Education, Naka", "college_of_education", "private"),
        ("City College of Education, Mararaba", "college_of_education", "private"),
        ("Cornerstone College of Education, Lagos", "college_of_education", "private"),
        ("Corona College of Education, Lekki", "college_of_education", "private"),
        ("Delar College of Education, Ibadan", "college_of_education", "private"),
        ("Diamond College of Education, Aba", "college_of_education", "private"),
        ("Elder Oyama Memorial College of Education, Obubra", "college_of_education", "private"),
        ("Festmed College of Education, Ajewa", "college_of_education", "private"),
        ("Havard Wilson College of Education, Aba", "college_of_education", "private"),
        ("Hill College of Education, Gwanje", "college_of_education", "private"),
        ("Hope and Anchor College of Education, Suleja", "college_of_education", "private"),
        ("Imam Saidu College of Education, Funtua", "college_of_education", "private"),
        ("Institute of Ecumenical Education, Enugu", "college_of_education", "private"),
        ("Kinsey College of Education, Ilorin", "college_of_education", "private"),
        ("Kwararafa College of Education, Otukpo", "college_of_education", "private"),
        ("Lessel College of Education, Lessel", "college_of_education", "private"),
        ("Muftau Olanihun College of Education, Ibadan", "college_of_education", "private"),
        ("Nana Aishat Memorial College of Education, Ilorin", "college_of_education", "private"),
        ("Onit College of Education, Abagana", "college_of_education", "private"),
        ("Oswald Waller College of Education, Shendam", "college_of_education", "private"),
        ("Pan-African College of Education, Offa", "college_of_education", "private"),
        ("Peaceland College of Education, Enugu", "college_of_education", "private"),
        ("Piaget College of Education, Abeokuta", "college_of_education", "private"),
        ("Royal College of Education, Ogun State", "college_of_education", "private"),
        ("St Augustine’s College of Education, Akoka", "college_of_education", "private"),
        ("St Frances Assisi College of Education, Zaria", "college_of_education", "private"),
        ("Steady Flow College of Education, Ikom", "college_of_education", "private"),
        ("Sunnah College of Education, Bauchi", "college_of_education", "private"),
        ("Topmost College of Education, Ipaja", "college_of_education", "private"),
        ("Union College of Education, Nsukka", "college_of_education", "private"),
        ("Yewa Central College of Education, Ayetoro", "college_of_education", "private"),
    ]

    # Cleanup existing institutions to avoid conflicts during re-seed
    # Warning: This deletes existing institutions. Only use in development.
    Institution.objects.all().delete()

    created_count = 0
    for name, inst_type, inst_category in institutions_data:
        # Generate a unique slug based on name and category to avoid collisions
        base_slug = slugify(name)
        slug = f"{base_slug}-{inst_category}"
        
        Institution.objects.get_or_create(
            slug=slug,
            defaults={
                'name': name,
                'inst_type': inst_type,
                'inst_category': inst_category
            }
        )
        created_count += 1

    print(f"Successfully seeded {created_count} institutions.")

if __name__ == "__main__":
    seed_institutions()
