# Generated by Django 6.0.1 on 2026-01-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='inst_category',
            field=models.CharField(choices=[('federal', 'Federal'), ('state', 'State'), ('private', 'Private')], default='federal', max_length=50),
        ),
        migrations.AddField(
            model_name='institution',
            name='inst_type',
            field=models.CharField(choices=[('university', 'University'), ('polytechnic', 'Polytechnic'), ('college_of_education', 'College of Education')], default='university', max_length=50),
        ),
    ]
