# Generated by Django 5.1.7 on 2026-01-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('MEETUP', 'Meet on Campus'), ('PLUG_DELIVERY', 'Plug Delivery'), ('TRIBE_RUNNER', 'Tribe Runner'), ('WAYBILL', 'Plug Waybill'), ('TRIBE_LOGISTICS', 'Tribe Logistics')], default='MEETUP', max_length=20),
        ),
    ]
