# Generated by Django 5.1.7 on 2026-01-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('DELIVERED', 'Delivered'), ('DISPUTED', 'Disputed')], default='RECEIVED', max_length=20),
        ),
    ]
